Remove unnecessary variable 'item'
This variable is not needed and can thus be removed.

This fixes a Bug which will print errors to Firefox error console:

    Zeitstempel: 03.04.2014 17:02:35
    Fehler: ReferenceError: assignment to undeclared variable item
    Quelldatei: chrome://httpsfinder/content/Overlay.js
    Zeile: 171

(could be translated to:)

    Timestamp: ...
    Error: ReferenceError: assignment to undeclared variable item
    Source file: chrome://httpsfinder/content/Overlay.js
    Line: 171